### ISSUE TITLE
 Esportazione data di Nascita - Birth date export

### ISSUE THREAD

**Issue by trivius86** [Big-Data-FC/scraper#11]
sorry if I open another one but the old post is closed 

In the meantime, I thank you as always for your availability.

I first tried to add your portion of code immediately below and launched the command, but it told me that the "player_url" was not declared.

So I went to the top of the code, where there is team_url and I also added:
"player_url": player.css("td:nth-child(2) a::attr(href)").get(),
Which was in the item list immediately below.

Also in item I added this:
"player_meta": self.parse_player(player_url),

and launched the script but unfortunately the player meta column is completely empty.

I attach a screenshot of the entire code
![immagine](https://github.com/Big-Data-FC/scraper/assets/54851168/b03e4557-7c15-4539-b07d-27e1c86ae2a7)

**Comment by trivius86** [comment]
In the meantime I solved part of the problem
req = requests.get(
             SITE_BASE_URL + player_url ,

here the part of the year code had to be removed because the player url link has it automatically.

My problem now, however, is in capturing precisely that data.
If I use .meta as you wrote, the field remains empty. If I try to insert .info it will get the full name of the player (confirms that the code arrives on the page)... I'm trying them all but I think perhaps the problem could be the ::text or something else is needed.

I'll show you the html part of the site

<div class="col col-12">
<div class="bp3-card player">
<img alt data-src="https://cdn.sofifa.net/players/231/747/23_120.png" data-srcset="https://cdn.sofifa.net/players/231/747/23_240 .png 2x, https://cdn.sofifa.net/players/231/747/23_360.png 3x" alt src="https://cdn.sofifa.net/player_0.svg" data-root="https: //cdn.sofifa.net/" data-type="player">
<div class="info"><h1>Kylian Mbappé Lottin</h1>
<div class="meta ellipsis"><a rel="nofollow" href="/players?na=18" title="France"><img alt src="https://cdn.sofifa.net/pixel. gif" data-src="https://cdn.sofifa.net/flags/fr.png" data-srcset="https://cdn.sofifa.net/flags/fr@2x.png 2x, https:/ /cdn.sofifa.net/flags/fr@3x.png 3x" class="flag" width="21" height="16"></a> <span class="pos pos25">ST</span> <span class="pos pos27">LW</span> 23y.o. (Dec 20, 1998) 182cm / 6'0" 75kg / 165lbs</div>
</div>

**Comment by trivius86** [comment]
Ho RISOLTO facendo così , spero possa essere di aiuto anche ad altri
<img width="818" alt="Screenshot 2023-09-19 alle 10 23 26" src="https://github.com/Big-Data-FC/scraper/assets/54851168/fccfc426-533e-4091-a541-21138670a25d">

**Comment by davquar** [comment]
Great! Happy that you succeeded
