### ISSUE TITLE
Overall e Potenziale

### ISSUE THREAD

**Issue by trivius86** [Big-Data-FC/scraper#3]
Salve, complimenti per il vostro scrap che funziona una favola. Ma la favola si è infranta quando mi sono accorto che di tutti i valori purtroppo mancano due campi molto importanti, cioè l'overall e il potenziale. C'è il BOV cioè il BEST OVERALL ma non è utile essendo il top valore che hanno mai raggiunto e spesso non corrisponde in quello attuale. 

Ho verificato il codice, ma non riesco ad aggiungere il campo, in Sofifa.py ho aggiunto la riga:
  "ove": player.css("td.col-oa::text").get(),
Il td l'ho verificato sul sorgente del sito, ma purtroppo mi lascia il campo vuoto. 

Cosa sbaglio o cosa si può fare? Grazie.

**Comment by davquar** [comment]
Hi, you can solve it by adding a space before `::text`, so the line becomes `"ove": player.css("td.col-oa ::text").get()`

See the [Parsel documentation](https://parsel.readthedocs.io/en/latest/usage.html#extensions-to-css-selectors) for more info about this syntax
